language: python

sudo: false

env:
  matrix:
    - LUA="lua 5.3"

before_install:
  - pip install hererocks
  - hererocks here -r^ --$LUA # Install latest LuaRocks version
                              # plus the Lua version for this build job
                              # into 'here' subdirectory
  - export PATH=$PATH:$PWD/here/bin # Add directory with all installed binaries to PATH
  - eval `luarocks path --bin`
  - bin/dev-setup

install:
  - luarocks make

script:
  - busted -c

after_success:
  - luacov-coveralls -v

notifications:
  email:
    on_success: change
    on_failure: always

